devgithuka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.flatpages import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include ('weblog.urls')),
    path('projects/', include ('projects.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    #url(r'^pages/', include('django.contrib.flatpages.urls')),
    path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    path('gnupg/', views.flatpage, {'url': '/gnupg/'}, name='gnupg'),

]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='home'),
    ]

projects/urls.py
from django.urls import path

# Specifies the app name for name spacing.
app_name = 'projects'

# Blog application imports.
from projects.views import (
    ProjectListView,
    ProjectDetailView,
    #ProjectSearchListView,
)

# Project/urls.py
urlpatterns = [

    # Project URLS #

    # /home/
    path(
        route='',
        view=ProjectListView.as_view(),
        name='projects_list'
    ),

    path(
        route='<str:slug>/',
        #route='<str:slug>/',
        view=ProjectDetailView.as_view(),
        name='projects_detail'
    ),]

    # path(
    #      route='project/search/',
    #      view=ProjectSearchListView.as_view(),
    #      name='project_search_list'

    #  ),]

weblog/urls.py
from django.urls import path

# Specifies the app name for name spacing.
app_name = 'weblog'

# Blog application imports.
from weblog.views import (
    PostListView,
    PostDetailView,
    PostSearchListView,
)

# post/urls.py
urlpatterns = [

    # POST URLS #

    # /home/
    path(
        route='',
        view=PostListView.as_view(),
        name='post_list'
    ),

    path(
        route='<str:slug>/',
        #route='<str:slug>/',
        view=PostDetailView.as_view(),
        name='post_detail'
    ),

    path(
         route='post/search/',
         view=PostSearchListView.as_view(),
         name='post_search_list'

     ),]

home/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse
from django.utils import timezone

## AutoSlug Modules
from autoslug import AutoSlugField

from ckeditor_uploader.fields import RichTextUploadingField 

STATUS = (
    (0, "Draft"),
    (1, "Publish"))


class Project(models.Model):
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='projects_author')
    title = models.CharField(max_length=250, null = True)
    description = RichTextUploadingField(null = True)
    tagline = models.CharField(max_length=250, null = True)
    budget = models.CharField(max_length=250, null = True)
    slug = AutoSlugField(populate_from='title', null = True)
    progress = models.IntegerField(null = True)
    github = models.CharField(max_length=250, null = True)
    image = models.ImageField(upload_to='media/images/', blank=True)
    manuals = models.FileField(upload_to='manuals/', null=True, blank=True, help_text='Manuals')
    created_on = models.DateTimeField(default=timezone.now)


    class Meta:

        ordering = ['-created_on']

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('projects:projects_detail', kwargs={'slug': self.slug})

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views.generic import (
    DetailView,
    ListView)

def index(request):
    context = {}
    return render(request, 'home.html', context=context)

projects/views.py
# Standard Python Library imports.
from functools import reduce
import operator

# Core Django imports.
from django.contrib import messages
from django.db.models import Q
from django.db.models import Count
from django.views.generic import (
    DetailView,
    ListView,
)

# Weblog application imports.
from .models import Project

class ProjectListView(ListView):
    context_object_name = "projects"
    paginate_by = 12
    #queryset = Documents.objects.filter(status=Post.PUBLISHED, deleted=False)
    queryset = Project.objects.all()
    template_name = "projects.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['categories'] = Category.objects.filter(approved=True)
        return context

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'projects_detail.html'

    def get_context_data(self, **kwargs):
        session_key = f"viewed_project {self.object.title}"
        if not self.request.session.get(session_key, False):
            #self.object.views += 1
            self.object.save()
            self.request.session[session_key] = True

        # kwargs['related_docyments'] = \
        #     Document.objects.filter(category=self.object.category).order_by('?')[:3]
        kwargs['project'] = self.object
        #kwargs['comment_form'] = CommentForm()
        return super().get_context_data(**kwargs)


# class PostSearchListView(ListView):
#     model = Post
#     paginate_by = 12
#     context_object_name = 'search_results'
#     template_name = "posts_search.html"

#     def get_queryset(self):
        
#         query = self.request.GET.get('q')

#         if query:
#             query_list = query.split()
#             search_results = Equipment.objects.filter(
#                 reduce(operator.and_,
#                        (Q(title__icontains=q) for q in query_list)) |
#                 reduce(operator.and_,
#                        (Q(content__icontains=q) for q in query_list)) |
#                 reduce(operator.and_,
#                         (Q(status__icontains=q) for q in query_list))
#             )

#             if not search_results:
#                 messages.info(self.request, f"No results for '{query}'")
#                 return search_results
#             else:
#                 messages.success(self.request, f"Results for '{query}'")
#                 return search_results
#         else:
#             messages.error(self.request, f"Sorry you did not enter any keyword")
#             return []

#     def get_context_data(self, **kwargs):
#         """
#             Add categories to context data
#         """
#         context = super(PostSearchListView, self).get_context_data(**kwargs)
#         #context['categories'] = Category.objects.filter(approved=True)
#         return context

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h4>Weblog</h4>
</div>

    {% for post in posts %}
<div class="container">
    <div class="card mb-2">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-3">
                    <div class="ratio ratio-16x9">
                        <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
                    </div>
                </div>
                <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">
                    
                        <h2 class="card-title h5">
                                <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                                </a>
                        </h2>

                        <div class="text-muted">
                            <small>
                                Published {{ post.created_on }} by <strong>{{ post.author }}</strong>
                            </small>
                        </div>                    
                        <p class="card-text mb-auto py-2">{{ post.content|safe|striptags|truncatechars:300 }}</p>
                
                </div>
            </div>
        </div>
    </div>
</div>
   
    {% endfor %}

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

</head>
  <body>

    <main>
      <div class="container py-4">
        <header class="pb-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>GNP-Githuka Noteonomy Project</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
            <span class="fs-4">Wilfred Githuka 楚大洋 </span>
          </a>
        </header>
      </div>

      {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

templates/gpupg.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h4>GNUPG Public Key</h4>
</div>

If you want to send me encrypted mail you will need to import my GPG public key into your keychain. As of February 19, 2014, my GPG public key ID is: 0x8cb0d0acb5cd81ec209c6cdfbd1a0e09c2f836c0

You can import my key by downloading it and then importing it:

D8E682D7CB2D9E0D174B2942E52DA6ED6D6C44B1

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      
      <p class="lead text-muted">Embeeded Systems | IoT | Low Level C | On this site is a collection of my projects. Some are complete while others require some more time to be done. Bridging the technology gap between my continent and the rest of the world</p>
      <p>
        <a href="{% url "weblog:post_list" %}" class="btn btn-primary my-2">DevLogs 手册</a>
        <a href="{% url "projects:projects_list" %}" class="btn btn-secondary my-2">Projects 项目</a>
        <a href="#" class="btn btn-secondary my-2">Ham Radio 5Z4WG</a>
        <a href="{% url "about" %}" class="btn btn-secondary my-2">About 关于我</a>
        <a href="{% url "gnupg" %}" class="btn btn-secondary my-2">GPG Public Key</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/gnp.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> GNP: The Githuka Noteonomy Project is a IoT based vehicle technology which is aware of its enviornment.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 30% Complete</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/c.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> LCHW: Learn C The Hard Way - Famous C tutorial by the author Zed A.Shaw. An opportunity to understand C deeper.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 9% Complete</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/zesta2.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> zesta2: An improvement of the first zesta project. This will be a complete make-from-scratch laptop power supply module.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 23% Complete</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/kanyoni.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> kanyoni-kaja: An ESP-32 solar powered bird cage that has a camera & wifi.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 6% Complete</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/cv.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> cv: My self-updating CV served in pdf by Latex</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 2% Complete</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="card-img-top" src="https://devgithuka.ap-south-1.linodeobjects.com/107.jpg" alt="Card image">
            <div class="card-body">
              <p class="card-text"> 107DaysofCode: Horning my coding skills from 15th September to 31st December 2022.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                <a href="" class="btn btn-sm btn-outline-secondary ">View More</a>
                </div>
                <small class="text-muted">Progress: 16% Complete</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

{% endblock %}

templates/posts.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h4>Weblog</h4>
</div>

    {% for post in posts %}
<div class="container">
    <div class="card mb-2">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-3">
                    <div class="ratio ratio-16x9">
                        <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
                    </div>
                </div>
                <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">
                    
                        <h2 class="card-title h5">
                                <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                                </a>
                        </h2>

                        <div class="text-muted">
                            <small>
                                Published {{ post.created_on }} by <strong>{{ post.author }}</strong>
                            </small>
                        </div>                    
                        <p class="card-text mb-auto py-2">{{ post.content|safe|striptags|truncatechars:300 }}</p>
                
                </div>
            </div>
        </div>
    </div>
</div>
   
    {% endfor %}

{% endblock content %}

templates/posts_detail.html
{% extends 'base.html' %}

{% block title %} - {{post.title}}{% endblock title %}

{% block content %}
<div class="container">
    <article>
        <figure>
         <img src="{{ post.image.url }}" class="rounded" alt="{{post.title}}">
        </figure>
        <div class="mt-3">
            <h1>{{post.title}}</h1>
            <p class="text-muted">
                Published {{ post.created_on }} by <strong>{{ post.author }}</strong>
            </p>
        </div>

        <div class="article-body">
                {{post.content|safe}}
        </div>
        
    </article>
</div>   
{% endblock content %}

templates/projects.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h4>Projects</h4>
</div>

{% for project in projects %}
<div class="container">
    
    <div class="card mb-2">
        <div class="card-body">
            <div class="row g-0">
                <div class="col-md-3">
                    <div class="ratio ratio-16x9">
                        <img src="{{ project.image.url }}" class="rounded" alt="{{project.title}}">
                    </div>
                </div>
                <div class="col-md-7 ps-md-3 pt-3 pt-md-0 d-flex flex-column">
                    
                        <h2 class="card-title h5">
                                <a href="{{ project.get_absolute_url }}">
                                {{ project.title }}
                                </a>
                        </h2>

                        <div class="text-muted">
                            <small>
                                进步: {{ project.progress }}% 开始: {{ project.created_on }} Budget {{ project.budget }}
                            </small>
                        </div>                    
                        <p class="card-text mb-auto py-2">{{ project.description|safe|striptags|truncatechars:200 }}</p>
                
                </div>
            </div>
        </div>
    </div>
</div>
   
{% endfor %}

{% endblock content %}

templates/projects_detail.html
{% extends 'base.html' %}

{% block title %} - {{project.title}}{% endblock title %}

{% block content %}
<div class="container">
    <article>
        <figure>
         <img src="{{ project.image.url }}" class="rounded" alt="{{project.title}}">
        </figure>
        <div class="mt-3">
            <h1>{{project.title}}</h1>
            <h3>{{project.tagline}}</h3>
            <p class="text-muted">
                Start: {{ project.created_on }} | 
                Progress: {{ project.progress }}% | 
                Github: {{ project.github }} | 
                Budget: {{ project.budget }}
            </p>
            <p class="text-muted">
                Project Manual(PDF): {{ project.manuals }} 
            </p>
        </div>

        <div class="article-body">
                {{project.description|linebreaks}}
        </div>
        
    </article>
</div> 

{% endblock content %}